name: ICMPvPBox
author: Shurisko, Zomboglace
website: https://icm.net/
version: ALPHA^0.1
main: fr.icm.PvPBox
commands:
  kit:
    aliases:
      - kits
      - k
  party:
    aliases:
      - groupe
      - group
      - p
      - g
  message:
    aliases:
      - msg
      - m
      - w
      - whisper
      - whisp
      - mp
      - dm
  reply:
    aliases:
      - r
      - resend
      - respond
  zone:
    aliases:
      - adminzone
      - azone
      - zones
      - icmzones
  akit:
    aliases:
      - adminkit
      - adminkits
      - akits
      - kitadmin
      - kitaccess
      - adminkitaccess
      - setkitaccess
  account:
    aliases:
      - accountmanager
      - manageaccount
      - playermanager
      - pmanage
      - aplayer

